runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Fri Jul 10 14:08:11 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Sun Jul 12 10:59:03 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
1
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runcell(0, 'C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Mon Jul 13 16:05:17 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/untitled0.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
1
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/untitled1.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/work around attempt 2.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Tue Jul 14 12:19:08 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/work around attempt 2.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Tue Jul 14 15:25:20 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/work around attempt 2.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/work around attempt 1.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/SQL create snippet.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Wed Jul 15 14:47:26 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')