runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Wed Jul 22 12:51:39 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Wed Jul 22 17:02:07 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Thu Jul 23 11:46:13 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/untitled0.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Thu Jul 23 14:00:22 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Mon Jul 27 12:32:43 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Tue Jul 28 20:54:05 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Tue Jul 28 21:13:15 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Tue Jul 28 21:16:27 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/cloud_sql_connector.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
%tb
runfile('C:/Users/Aaron Goldstein/.spyder-py3/cloud_sql_connector.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Fri Jul 31 13:37:12 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/cloud_sql_connector.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
%tb
runfile('C:/Users/Aaron Goldstein/.spyder-py3/cloud_sql_connector.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/untitled0.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
Agold123
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Clash_Functions.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/untitled1.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')