runfile('C:/Users/Aaron Goldstein/.spyder-py3/Stonk_Clash.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Mon Jul 20 17:43:02 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Mon Jul 20 18:25:36 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Tue Jul 21 16:39:10 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Tue Jul 21 16:52:11 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Wed Jul 22 12:51:39 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Wed Jul 22 17:02:07 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Thu Jul 23 11:46:13 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/untitled0.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')

## ---(Thu Jul 23 14:00:22 2020)---
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/DB_MGMT.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')
runfile('C:/Users/Aaron Goldstein/.spyder-py3/reconfigure.py', wdir='C:/Users/Aaron Goldstein/.spyder-py3')